// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NoviBet_Api.Core.Models;

public partial class CurrencyRate
{
    public string CurrencyCode { get; set; }

    public decimal Rate { get; set; }

    public DateTime RateDate { get; set; }
}