// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NoviBet_Api.Core.Models;

public partial class NoviBetContext : DbContext
{
    public NoviBetContext(DbContextOptions<NoviBetContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CurrencyRate> CurrencyRates { get; set; }

    public virtual DbSet<Wallet> Wallets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CurrencyRate>(entity =>
        {
            entity.HasKey(e => new { e.CurrencyCode, e.RateDate });

            entity.Property(e => e.CurrencyCode).HasMaxLength(10);
            entity.Property(e => e.RateDate).HasColumnType("datetime");
            entity.Property(e => e.Rate).HasColumnType("decimal(18, 6)");
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Wallets__3214EC0706093DA5");

            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(10);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}