// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NoviBet_Api.Core.Models;

public partial class Wallet
{
    public long Id { get; set; }

    public decimal Balance { get; set; }

    public string Currency { get; set; }
}